### PR TITLE
[MAT-306] add maven_install target

### PR DESCRIPTION
**Pull request by stuartarchibald**
This change simply adds in the target `maven_install` to the CMake command list.
The variables `maven_VERSION{_MAJOR,_MINOR,_PATCH,""}` combine to give a version for the installed jar. If I recall correctly, the prototype got to 0.0.29 so I promote the new version to start at 0.1.0. 
The javadoc generation needs sorting, has ticket [MAT-321](http://jira.opengamma.com/browse/MAT-321) (Generate javadocs & update maven install command to include them).

Buildbot gains a maven install step and passes:
BB Pass: [http://devmaths-lx-1:8011/builders/nyqwk2-testing/builds/625](http://devmaths-lx-1:8011/builders/nyqwk2-testing/builds/625)
No change to coverage.

### CODE REVIEW

**Comment by gmarkall** [comment]
Shouldn't the "Longdog" and maven versions match each other? Otherwise, I think we might be setting ourselves up for confusion in the future when the jar names don't match the version number.

**Comment by stuartarchibald** [comment]
I've refactored the CMake so that the java naming propagates throughout the build hopefully making it cleaner. As to versions, the jars are built and named as `"${PROJECT_NAME}-${maven_VERSION}-SNAPSHOT"` as a root name, this is the same naming as what gets installed in a maven repo.
BB Pass: [http://devmaths-lx-1:8011/builders/nyqwk2-testing/builds/626](http://devmaths-lx-1:8011/builders/nyqwk2-testing/builds/626)

**Comment by gmarkall** [comment]
Great, thanks, and apologies for anything that could be considered bikeshedding! Buildbot pass noted: http://devmaths-lx-1:8011/builders/nyqwk2-testing/builds/626

Merging.

**Comment by stuartarchibald** [comment]
No worries, it really needed sorting regardless of when or how :)

**Pull request merged**
