### PR TITLE
[MAT-199] Check for null args on construction.

### PR DESCRIPTION
**Pull request by gmarkall**
Unfortunately there seems to be no way to get rid of OGExpr(),
because of the one- and two-argument constructors of OGUnaryExpr
and OGBinaryExpr. However, OGExpr objects will never end up with
null args as long as OGExpr subclass constructors always ensure
that setArgs() is called if the use the default OGExpr()
constructor.

### CODE REVIEW

**Comment by gmarkall** [comment]
Buildbot pass: http://devmaths-lx-1:8011/builders/nyqwk2-testing/builds/80

**Comment by gmarkall** [comment]
Updated to remove noarg constructors, and stop OGExpr::_args being set as null.

Buildbot pass: http://devmaths-lx-1:8011/builders/nyqwk2-testing/builds/81

**Comment by gmarkall** [comment]
Removed the OGUnaryExpr(arg) and OGBinaryExpr(arg1, arg2) ctors. Buildbot pass: http://devmaths-lx-1:8011/nyqwk2-testing/builds/82

**Comment by stuartarchibald** [comment]
Changes made as discussed off line i.e. removing default FOO::FOO(void){}; 

Cleans things up a lot, good change set, happy to merge.

**Pull request merged**
