### PR TITLE
Generation of expression nodes.

### PR DESCRIPTION
**Pull request by gmarkall**
This PR allows the generation of nodes and their implementations in RDAG and JShim by their addition in the Python generator, without needing and C++ source code changes. 

This consists of the following changes:
- Removal of manually-written SVD code
- Moving the Python generator into a separate subfolder so it can be used by RDAG and JShim.
- Addition of Unary and Binary expressions' enum types to the java ExprTypeEnum
- Generation of the enum values on the C++ side
- Some refactoring of the generator so that nodes have consistent behaviour (e.g. so that all nodes have a typename and an enumname that can be referred to consistently). The base baehviour is in exprtree.py
- UndefinedUnary/Binary expression nodes, that act as placeholders whilst we work through implementing them. All Unary and Binary nodes from our spreadsheet of nodes are now listed in the generator.
- Support for generation of runners that do their computation by calling a function. This is demonstrated for the sine function only at present.
- Implementation of JOGIntegerScalar and JOGLogicalMatrix, since the generator expected their presence (in order to keep everything consistent).
- Generation of the switch table in the expression factory so that the conversion from Java objects to C++ objects is automated.

Buildbot pass: http://devmaths-lx-1:8011/builders/nyqwk2-testing/builds/506

### CODE REVIEW

**Comment by gmarkall** [comment]
Removed pyprimes dependency. Buildbot pass: http://devmaths-lx-1:8011/builders/nyqwk2-testing/builds/507

**Comment by stuartarchibald** [comment]
thanks :)

**Comment by gmarkall** [comment]
Buildbot pass after fixing up headers: http://devmaths-lx-1:8011/builders/nyqwk2-testing/builds/508

**Comment by stuartarchibald** [comment]
Excellent. Good job. This completes a lot of the templating work needed. Happy to merge.

**Pull request merged**
